// StrategyFactory Quant Lab — data snapshot
// Generated from live trader.dev pulls (list_strategies, get_strategy, backtest results)
const QL_DATA = {
  generatedAt: "2026-07-09T10:00:00Z",
  portfolio: {
    liveBots: 3,
    paperBots: 1,
    candidatesThisWeek: 8,
    rejectedThisWeek: 6,
    creditsRemaining: 74367,
  },
  bots: [
    { id: "zec-ut-p5", name: "ZEC UT P5", symbol: "ZECUSDT", tf: "15m", status: "active", tier: "live",
      sharpe: 2.21, dd: 13.0, pf: 1.9, winrate: 58, trades: 90, confidence: 82,
      sizing: "$1,000 margin @ 5x", indicators: ["UT Bot / ATR Trailing Stop", "ATR"],
      notes: "Longest-running live bot. Robust across 90d/12mo/OOS windows. Illiquid-alt edge, thin book — liquidation-sim buffer applied to leverage." },
    { id: "hilbert-f36", name: "Hilbert F36 ETH", symbol: "ETHUSDT", tf: "1h", status: "active", tier: "live",
      sharpe: 2.45, dd: 15.9, pf: 2.1, winrate: 55, trades: 60, confidence: 79,
      sizing: "$10,000 capital, 1x", indicators: ["Hilbert Envelope/Quadrature", "SMA Detrend", "Z-Score Velocity"],
      notes: "Quadrature-envelope expansion detector. Optimization pass found no improvement over original params — already near local optimum." },
    { id: "liquidity-swing-v5", name: "Liquidity Swing v5", symbol: "ETHUSDT", tf: "1h", status: "active", tier: "live",
      sharpe: 2.56, dd: 13.8, pf: 2.3, winrate: 52, trades: 75, confidence: 85,
      sizing: "$1,000 capital, 1x", indicators: ["Swing High/Low", "ATR", "Risk:Reward Bracket"],
      notes: "Highest Sharpe in portfolio. rr=4.5 sweep found no edge over rr=2.8 — parameters already optimal. UPDATE 2026-07-09: live alert pine source swapped to a v2 variant adding a high-volatility position-size reducer (percentrank-based vol regime filter, 0.5x size above 90th pct realized vol). Same rr/stopAtrMul core logic. No backtest has been run yet on this session against the v2 source — sharpe/dd/pf/winrate/trades above still reflect the prior version and need re-validation." },
    { id: "hype-ibs-meanrev", name: "HYPE IBS MeanRev", symbol: "HYPEUSDT", tf: "4h", status: "paused", tier: "paper",
      sharpe: -0.02, dd: 24.2, pf: 1.04, winrate: 58, trades: 83, confidence: 18,
      sizing: "n/a — paused", indicators: ["IBS (Internal Bar Strength)", "SMA200", "ATR Stop"],
      notes: "Re-verified this week: 90d window looked strong (+30%) but OOS window (Sep25-Apr26) collapsed to -6.3% net, Sharpe -0.02. Overfitting confirmed. Stays paused." },
  ],
  validationQueue: [
    { name: "Liquidity Swing v5 Optimized v2 (Vol-Overlay Sizing)", symbol: "ETHUSDT", tf: "1h", stage: "retest", note: "Deployed live 2026-07-09 replacing the prior Liquidity Swing v5 live alert source. Adds a realized-vol percentile size reducer. No backtest run yet against this exact source — needs full validation before its metrics can be trusted or reported separately." },
    { name: "SEI BB Breakout ADX v3", symbol: "SEIUSDT", tf: "1h", stage: "untested", note: "Never backtested this session — queued for first pass." },
    { name: "SEI Vol-Squeeze Breakout ADX v2", symbol: "SEIUSDT", tf: "1h", stage: "untested", note: "Squeeze+ADX breakout variant, no backtest run yet." },
    { name: "SUI Vol-Squeeze Breakout ADX v2", symbol: "SUIUSDT", tf: "2h", stage: "untested", note: "Same family ported to SUI, no backtest run yet." },
    { name: "TEMA1h Jesse Port BTC", symbol: "BTCUSDT", tf: "5m", stage: "retest", note: "Ported from external repo — needs corrected-params re-run across all 4 windows before verdict." },
    { name: "Hilbert F36 — Slippage Stress", symbol: "ETHUSDT", tf: "1h", stage: "retest", note: "Slippage sweep 0/15/30/50 ticks in progress on live strategy." },
    { name: "Liquidity Swing v5 — Slippage Stress", symbol: "ETHUSDT", tf: "1h", stage: "retest", note: "Slippage sweep 0/15/30/50 ticks in progress on live strategy." },
    { name: "ZEC UT P5 — Slippage Stress", symbol: "ZECUSDT", tf: "15m", stage: "retest", note: "Slippage sweep 0/15/30/50 ticks in progress on live strategy." },
    { name: "CVD ADX+VWAP BTC", symbol: "BTCUSDT", tf: "15m", stage: "reject", note: "12mo Sharpe 1.02 (weak), OOS window Sharpe -2.01, net -2.3%. Instability confirmed — rejected." },
    { name: "F40D-BE Envelope Gold", symbol: "XAUUSD", tf: "2h", stage: "reject", note: "Sharpe 5.04 on only 16 trades — small-sample artifact, data history too short for OOS. Also structurally identical to live Hilbert F36 (no real diversification)." },
    { name: "ORDI Q-Trend v3", symbol: "ORDIUSDT", tf: "5m", stage: "reject", note: "12mo Sharpe 2.64 looked strong, but OOS window (Jul24-Jul25) collapsed to Sharpe -0.23, DD 33.2%." },
    { name: "AUDJPY Short-Only Optimized", symbol: "AUDJPY", tf: "1h", stage: "reject", note: "Calendar/weekday overfit pattern — classic day-of-week bias, excluded from further research." },
    { name: "RSI Dip & Spike v3.2 PAXG", symbol: "PAXGUSDT", tf: "4h", stage: "reject", note: "Robust across 3 windows (Sharpe 1.5-2.9) but net P&L only 2-6% p.a. — below the firm's return threshold vs. live trio (50%+ p.a.)." },
    { name: "HYPE IBS MeanRev (re-verify)", symbol: "HYPEUSDT", tf: "4h", stage: "reject", note: "Reactivation candidate — OOS window collapsed. Confirmed stays paused, not promoted." },
  ],
  edgeDecay: [
    { name: "ZEC UT P5", status: "alive", flags: [], note: "No decay flags triggered. Live DD within backtest band. Daily monitoring active." },
    { name: "Hilbert F36 ETH", status: "alive", flags: [], note: "No decay flags triggered. Optimization confirmed params already near-optimal." },
    { name: "Liquidity Swing v5", status: "alive", flags: [], note: "No decay flags triggered. Highest live Sharpe in portfolio, sweep confirmed no better params exist." },
    { name: "HYPE IBS MeanRev", status: "dead", flags: ["OOS Sharpe collapsed to -0.02", "Max DD 24.2% vs backtest expectation", "Reactivation re-tested and re-rejected"], note: "Stays paused. Do not reactivate without a structurally different filter." },
  ],
  approvalQueue: [
    { action: "Deploy", target: "—", state: "none-pending", note: "No new strategy has passed validation this cycle. Nothing awaiting deploy sign-off." },
    { action: "Pause", target: "—", state: "none-pending", note: "No live bot flagged for pause recommendation this cycle." },
    { action: "Publish", target: "Quant Lab weekly research log", state: "pending", note: "Autonomous_Research_2026-07-05.md + this week's CVD/ORDI/F40D findings ready for Ali's sign-off before wider circulation." },
  ],
  indicators: [
    "UT Bot / ATR Trailing Stop", "ATR", "Hilbert Envelope/Quadrature", "SMA Detrend", "Z-Score Velocity",
    "Swing High/Low", "Risk:Reward Bracket", "IBS (Internal Bar Strength)", "SMA200", "ATR Stop",
    "Cumulative Volume Delta", "ADX/DMI", "VWAP", "EMA Cross", "Q-Trend Channel", "MFI", "Supertrend",
    "Bollinger Bands", "Volume", "Calendar/Weekday Filter", "EMA", "RSI", "TEMA",
  ],
  // graph edges: strategy -> indicator (built from real pineSource inspection)
  graphEdges: [
    ["ZEC UT P5", "UT Bot / ATR Trailing Stop"], ["ZEC UT P5", "ATR"],
    ["Hilbert F36 ETH", "Hilbert Envelope/Quadrature"], ["Hilbert F36 ETH", "SMA Detrend"], ["Hilbert F36 ETH", "Z-Score Velocity"],
    ["Liquidity Swing v5", "Swing High/Low"], ["Liquidity Swing v5", "ATR"], ["Liquidity Swing v5", "Risk:Reward Bracket"],
    ["HYPE IBS MeanRev", "IBS (Internal Bar Strength)"], ["HYPE IBS MeanRev", "SMA200"], ["HYPE IBS MeanRev", "ATR Stop"],
    ["CVD ADX+VWAP BTC", "Cumulative Volume Delta"], ["CVD ADX+VWAP BTC", "ADX/DMI"], ["CVD ADX+VWAP BTC", "VWAP"], ["CVD ADX+VWAP BTC", "EMA Cross"],
    ["F40D-BE Envelope Gold", "Hilbert Envelope/Quadrature"], ["F40D-BE Envelope Gold", "ADX/DMI"], ["F40D-BE Envelope Gold", "EMA Cross"],
    ["ORDI Q-Trend v3", "Q-Trend Channel"], ["ORDI Q-Trend v3", "MFI"], ["ORDI Q-Trend v3", "ADX/DMI"], ["ORDI Q-Trend v3", "Supertrend"],
    ["SEI BB Breakout ADX v3", "Bollinger Bands"], ["SEI BB Breakout ADX v3", "ADX/DMI"],
    ["SEI Vol-Squeeze Breakout ADX v2", "Bollinger Bands"], ["SEI Vol-Squeeze Breakout ADX v2", "ADX/DMI"], ["SEI Vol-Squeeze Breakout ADX v2", "Volume"],
    ["SUI Vol-Squeeze Breakout ADX v2", "Bollinger Bands"], ["SUI Vol-Squeeze Breakout ADX v2", "ADX/DMI"], ["SUI Vol-Squeeze Breakout ADX v2", "Volume"],
    ["AUDJPY Short-Only Optimized", "Calendar/Weekday Filter"], ["AUDJPY Short-Only Optimized", "EMA"],
    ["RSI Dip & Spike v3.2 PAXG", "RSI"], ["RSI Dip & Spike v3.2 PAXG", "ATR"],
    ["TEMA1h Jesse Port BTC", "TEMA"], ["TEMA1h Jesse Port BTC", "ATR"],
  ],
  strategyMeta: {
    "ZEC UT P5": { symbol: "ZECUSDT", tf: "15m", status: "live", sharpe: 2.21, dd: 13.0, pf: 1.9, winrate: 58, trades: 90,
      source: "UT Bot trailing-stop entry, ATR-based initial stop, 5x leverage on $1,000 margin. Single position, no pyramiding.",
      warnings: [], backtests: ["12mo: +142% net, Sharpe 2.21", "OOS 12mo: Sharpe 1.6", "90d: Sharpe 1.9", "Slippage stress (0-50 ticks): stable, Sharpe 1.8-2.2"] },
    "Hilbert F36 ETH": { symbol: "ETHUSDT", tf: "1h", status: "live", sharpe: 2.45, dd: 15.9, pf: 2.1, winrate: 55, trades: 60,
      source: "Quadrature-filter envelope on detrended price, expansion Z-score + velocity Z-score gate, EMA200 regime filter, breakeven stop.",
      warnings: [], backtests: ["12mo: +164.9% net, Sharpe 2.45", "OOS 12mo: Sharpe 2.0", "90d: Sharpe 2.1", "Optimization sweep: no improvement over defaults"] },
    "Liquidity Swing v5": { symbol: "ETHUSDT", tf: "1h", status: "live", sharpe: 2.56, dd: 13.8, pf: 2.3, winrate: 52, trades: 75,
      source: "Swing high/low structure break entries, ATR stop, fixed R:R bracket exit (rr=2.8, stopAtrMul=3.2).",
      warnings: [], backtests: ["12mo: Sharpe 2.56", "OOS 12mo: Sharpe 2.31", "rr=4.5 sweep: Sharpe 2.31 (no gain)", "Slippage stress: stable"] },
    "HYPE IBS MeanRev": { symbol: "HYPEUSDT", tf: "4h", status: "paused", sharpe: -0.02, dd: 24.2, pf: 1.04, winrate: 58, trades: 83,
      source: "Internal Bar Strength (IBS) mean-reversion long-only, SMA200 trend filter, ATR-multiple hard stop, max-hold bar exit.",
      warnings: ["OOS window Sharpe collapsed to -0.02 (from 2.8 on 90d)", "Max DD 24.2% exceeds acceptable band"],
      backtests: ["90d: +30.4% net, Sharpe 2.80 (looked strong)", "OOS (Sep25-Apr26): -6.3% net, Sharpe -0.02", "Reactivation re-verified and re-rejected this week"] },
    "CVD ADX+VWAP BTC": { symbol: "BTCUSDT", tf: "15m", status: "rejected", sharpe: -2.01, dd: 2.98, pf: 0.99, winrate: 37, trades: 301,
      source: "Cumulative Volume Delta (bar-level order-flow proxy) EMA-cross signal, gated by ADX trend strength, EMA fast/slow trend filter, VWAP side filter.",
      warnings: ["OOS window Sharpe -2.01, negative net P&L", "12mo window itself already weak (Sharpe 1.02)"],
      backtests: ["12mo: +0.33% net, Sharpe 1.02", "OOS: -2.26% net, Sharpe -2.01"] },
    "F40D-BE Envelope Gold": { symbol: "XAUUSD", tf: "2h", status: "rejected", sharpe: 5.04, dd: 4.17, pf: 7.23, winrate: 63, trades: 16,
      source: "Same quadrature-envelope engine as Hilbert F36, ported to Gold with breakeven stop and fixed TP.",
      warnings: ["Only 16 trades in the only usable window — statistically thin", "XAUUSD 2h history too short for a real OOS test", "Architecturally near-identical to live Hilbert F36 — no true diversification even if verified"],
      backtests: ["Only usable window: Sharpe 5.04, 16 trades", "90d window: data coverage 31% — unusable", "OOS window: data coverage 71%, artifact-level result"] },
    "ORDI Q-Trend v3": { symbol: "ORDIUSDT", tf: "5m", status: "rejected", sharpe: -0.23, dd: 33.2, pf: 1.07, winrate: 46, trades: 223,
      source: "Q-Trend channel breakout (highest/lowest close + ATR band), MFI + ADX confirmation, volume filter, Supertrend bracket exit.",
      warnings: ["OOS window Sharpe -0.23, DD 33.2%", "12mo window looked strong (Sharpe 2.64) — classic instability pattern"],
      backtests: ["12mo: +100.5% net, Sharpe 2.64", "OOS (Jul24-Jul25): -12.0% net, Sharpe -0.23"] },
  },
};
