// StrategyFactory Quant Lab — data snapshot
// Generated from live trader.dev pulls (list_strategies, get_strategy, backtest results)
const QL_DATA = {
  generatedAt: "2026-07-12T18:00:33Z",
  portfolio: {
    liveBots: 3,
    paperBots: 1,
    candidatesThisWeek: 8,
    rejectedThisWeek: 6,
    creditsRemaining: 1477,
  },
  bots: [
    { id: "zec-ut-p5", name: "ZEC UT P5", symbol: "ZECUSDT", tf: "15m", status: "active", tier: "live",
      sharpe: 2.29, dd: 16.4, pf: 2.02, winrate: 37, trades: 187, confidence: 82,
      sizing: "$1,000 margin @ 5x", indicators: ["UT Bot / ATR Trailing Stop", "ATR"],
      traderDevUrl: "https://mcp-api.trader.dev/backtest/01KX42TPTXNA4X5YGTS6A7BNN9",
      windows: [
        { label: "30d", netPct: 6.28, sharpe: 3.24, pf: 2.60, dd: 4.38, trades: 15, url: "https://mcp-api.trader.dev/backtest/01KX42TFP8DR7EP47T58ACRKH2" },
        { label: "90d", netPct: 38.56, sharpe: 4.91, pf: 4.10, dd: 5.50, trades: 36, url: "https://mcp-api.trader.dev/backtest/01KX42TJ68SRCX8CY1DASYY423" },
        { label: "120d", netPct: 49.33, sharpe: 4.71, pf: 3.48, dd: 5.45, trades: 52, url: "https://mcp-api.trader.dev/backtest/01KX42TMBJHV97A27N72RCPGGK" },
        { label: "365d", netPct: 100.87, sharpe: 2.29, pf: 2.02, dd: 16.37, trades: 187, url: "https://mcp-api.trader.dev/backtest/01KX42TPTXNA4X5YGTS6A7BNN9" },
      ],
      notes: "Longest-running live bot. Robust across all 4 windows (30/90/120/365d) — net P&L scales cleanly with window length, no OOS collapse. Illiquid-alt edge, thin book — liquidation-sim buffer applied to leverage." },
    { id: "hilbert-f36", name: "Hilbert F36 ETH", symbol: "ETHUSDT", tf: "1h", status: "active", tier: "live",
      sharpe: 3.78, dd: 15.1, pf: 3.08, winrate: 61, trades: 41, confidence: 79,
      sizing: "$10,000 capital, 1x", indicators: ["Hilbert Envelope/Quadrature", "SMA Detrend", "Z-Score Velocity"],
      traderDevUrl: "https://mcp-api.trader.dev/backtest/01KX42W9Z226JCBQ6FFFZ0WE7T",
      windows: [
        { label: "30d", netPct: 13.58, sharpe: 7.39, pf: null, dd: 4.46, trades: 2, lowSample: true, url: "https://mcp-api.trader.dev/backtest/01KX42W0WTJM2K45B73GX9YC72" },
        { label: "90d", netPct: 36.44, sharpe: 5.17, pf: 11.85, dd: 4.76, trades: 8, url: "https://mcp-api.trader.dev/backtest/01KX42W39XZCFQ32E944TZQ6FQ" },
        { label: "120d", netPct: 18.42, sharpe: 2.19, pf: 2.26, dd: 14.29, trades: 13, url: "https://mcp-api.trader.dev/backtest/01KX42W796QXAFSSSN8KR9CA0W" },
        { label: "365d", netPct: 170.47, sharpe: 3.78, pf: 3.08, dd: 15.10, trades: 41, url: "https://mcp-api.trader.dev/backtest/01KX42W9Z226JCBQ6FFFZ0WE7T" },
      ],
      notes: "Quadrature-envelope expansion detector. Optimization pass found no improvement over original params — already near local optimum. 30d window only has 2 trades — too thin to read into, treat 90d/365d as primary signal." },
    { id: "liquidity-swing-v5", name: "Liquidity Swing v5", symbol: "ETHUSDT", tf: "1h", status: "active", tier: "live",
      sharpe: 2.58, dd: 18.1, pf: 2.44, winrate: 49, trades: 51, confidence: 85,
      sizing: "$1,000 capital, 1x", indicators: ["Swing High/Low", "ATR", "Risk:Reward Bracket"],
      traderDevUrl: "https://mcp-api.trader.dev/backtest/01KX42XJM710K6TCFMBD20N6TC",
      windows: [
        { label: "30d", netPct: 11.52, sharpe: 3.11, pf: 2.83, dd: 10.49, trades: 7, url: "https://mcp-api.trader.dev/backtest/01KX42XC6XQNE0ACCKVQBN4CFC" },
        { label: "90d", netPct: 15.20, sharpe: 1.87, pf: 2.03, dd: 10.40, trades: 16, url: "https://mcp-api.trader.dev/backtest/01KX42XDZBBQRS16CXW28P2HMF" },
        { label: "120d", netPct: 22.21, sharpe: 1.85, pf: 2.08, dd: 10.54, trades: 20, url: "https://mcp-api.trader.dev/backtest/01KX42XFTHBPPCQYB75ZJCZ2CF" },
        { label: "365d", netPct: 193.06, sharpe: 2.58, pf: 2.44, dd: 18.06, trades: 51, url: "https://mcp-api.trader.dev/backtest/01KX42XJM710K6TCFMBD20N6TC" },
      ],
      notes: "Highest 365d Sharpe in portfolio. rr=4.5 sweep found no edge over rr=2.8 — parameters already optimal. UPDATE 2026-07-09: live alert pine source swapped to a v2 variant adding a high-volatility position-size reducer (percentrank-based vol regime filter, 0.5x size above 90th pct realized vol). Same rr/stopAtrMul core logic. Window table above reflects the ORIGINAL v5 source (re-verified today) — v2 has NOT been backtested yet and needs full re-validation before its numbers can be trusted or reported separately." },
    { id: "hype-ibs-meanrev", name: "HYPE IBS MeanRev", symbol: "HYPEUSDT", tf: "4h", status: "paused", tier: "paper",
      sharpe: 0.74, dd: 20.1, pf: 1.32, winrate: 59, trades: 139, confidence: 18,
      sizing: "n/a — paused", indicators: ["IBS (Internal Bar Strength)", "SMA200", "ATR Stop"],
      traderDevUrl: "https://mcp-api.trader.dev/backtest/01KX42Y6B0FQ57WS1KGG2D9VYE",
      windows: [
        { label: "30d", netPct: 0, sharpe: null, pf: null, dd: 0, trades: 0, noSignal: true, url: "https://mcp-api.trader.dev/backtest/01KX42Y1Q24JRDNRK3F2XBZPEE" },
        { label: "90d", netPct: 30.37, sharpe: 2.80, pf: 2.13, dd: 13.40, trades: 35 },
        { label: "120d", netPct: 22.74, sharpe: 1.83, pf: 1.70, dd: 13.40, trades: 52, url: "https://mcp-api.trader.dev/backtest/01KX42Y3YM83F2TNKZE0FFCDQN" },
        { label: "365d", netPct: 24.95, sharpe: 0.74, pf: 1.32, dd: 20.08, trades: 139, url: "https://mcp-api.trader.dev/backtest/01KX42Y6B0FQ57WS1KGG2D9VYE" },
      ],
      notes: "Re-verified this week: 90d window looked strong (+30.4%, Sharpe 2.8) but the OOS window (Sep25-Apr26, not shown in this 4-window set) collapsed to -6.3% net, Sharpe -0.02. 365d Sharpe 0.74 confirms weak long-run edge even before the OOS collapse. Overfitting confirmed. Stays paused. 30d window had zero signals — no trades fired in the last month. Note: 90d window result link unavailable — that backtest was run in a prior session without its resultId retained." },
  ],
  validationQueue: [
    { name: "Liquidity Swing v5 Optimized v2 (Vol-Overlay Sizing)", symbol: "ETHUSDT", tf: "1h", stage: "retest", note: "Deployed live 2026-07-09 replacing the prior Liquidity Swing v5 live alert source. Adds a realized-vol percentile size reducer. No backtest run yet against this exact source — needs full validation before its metrics can be trusted or reported separately." },
    { name: "SEI BB Breakout ADX v3", symbol: "SEIUSDT", tf: "1h", stage: "untested", note: "Never backtested this session — queued for first pass." },
    { name: "SEI Vol-Squeeze Breakout ADX v2", symbol: "SEIUSDT", tf: "1h", stage: "untested", note: "Squeeze+ADX breakout variant, no backtest run yet." },
    { name: "SUI Vol-Squeeze Breakout ADX v2", symbol: "SUIUSDT", tf: "2h", stage: "untested", note: "Same family ported to SUI, no backtest run yet." },
    { name: "TEMA1h Jesse Port BTC", symbol: "BTCUSDT", tf: "5m", stage: "retest", note: "Ported from external repo — needs corrected-params re-run across all 4 windows before verdict." },
    { name: "Hilbert F36 — Slippage Stress", symbol: "ETHUSDT", tf: "1h", stage: "retest", note: "Slippage sweep 0/15/30/50 ticks in progress on live strategy." },
    { name: "Liquidity Swing v5 — Slippage Stress", symbol: "ETHUSDT", tf: "1h", stage: "retest", note: "Slippage sweep 0/15/30/50 ticks in progress on live strategy." },
    { name: "ZEC UT P5 — Slippage Stress", symbol: "ZECUSDT", tf: "15m", stage: "retest", note: "Slippage sweep 0/15/30/50 ticks in progress on live strategy." },
    { name: "CVD ADX+VWAP BTC", symbol: "BTCUSDT", tf: "15m", stage: "reject", note: "12mo Sharpe 1.02 (weak), OOS window Sharpe -2.01, net -2.3%. Instability confirmed — rejected." },
    { name: "F40D-BE Envelope Gold", symbol: "XAUUSD", tf: "2h", stage: "reject", note: "Sharpe 5.04 on only 16 trades — small-sample artifact, data history too short for OOS. Also structurally identical to live Hilbert F36 (no real diversification)." },
    { name: "ORDI Q-Trend v3", symbol: "ORDIUSDT", tf: "5m", stage: "reject", note: "12mo Sharpe 2.64 looked strong, but OOS window (Jul24-Jul25) collapsed to Sharpe -0.23, DD 33.2%." },
    { name: "AUDJPY Short-Only Optimized", symbol: "AUDJPY", tf: "1h", stage: "reject", note: "Calendar/weekday overfit pattern — classic day-of-week bias, excluded from further research." },
    { name: "RSI Dip & Spike v3.2 PAXG", symbol: "PAXGUSDT", tf: "4h", stage: "reject", note: "Robust across 3 windows (Sharpe 1.5-2.9) but net P&L only 2-6% p.a. — below the firm's return threshold vs. live trio (50%+ p.a.)." },
    { name: "HYPE IBS MeanRev (re-verify)", symbol: "HYPEUSDT", tf: "4h", stage: "reject", note: "Reactivation candidate — OOS window collapsed. Confirmed stays paused, not promoted." },
  ],
  edgeDecay: [
    { name: "ZEC UT P5", status: "alive", flags: [], note: "No decay flags triggered. Live DD within backtest band. Net P&L scales cleanly across 30/90/120/365d windows." },
    { name: "Hilbert F36 ETH", status: "alive", flags: [], note: "No decay flags triggered. Optimization confirmed params already near-optimal. 30d sample is thin (2 trades) but 90d/365d remain strong." },
    { name: "Liquidity Swing v5", status: "soft", flags: ["Live source swapped to unvalidated v2 (vol-overlay sizing) — pending backtest"], note: "Original v5 remains robust across all windows. Flagged soft only because the LIVE alert now runs a different, not-yet-validated source (v2) than what these numbers reflect." },
    { name: "HYPE IBS MeanRev", status: "dead", flags: ["OOS Sharpe collapsed to -0.02", "Max DD 24.2% vs backtest expectation", "365d Sharpe only 0.74 — weak even pre-collapse", "Zero trades in the last 30 days", "Reactivation re-tested and re-rejected"], note: "Stays paused. Do not reactivate without a structurally different filter." },
  ],
  approvalQueue: [
    { action: "Deploy", target: "—", state: "none-pending", note: "No new strategy has passed validation this cycle. Nothing awaiting deploy sign-off." },
    { action: "Validate", target: "Liquidity Swing v5 Optimized v2", state: "pending", note: "Live alert source was swapped to v2 (vol-overlay sizing) without a fresh 4-window backtest — needs validation before we can trust it's still performing like v5." },
    { action: "Publish", target: "Quant Lab weekly research log", state: "pending", note: "Autonomous_Research_2026-07-05.md + this week's CVD/ORDI/F40D findings ready for Ali's sign-off before wider circulation." },
  ],
  indicators: [
    "UT Bot / ATR Trailing Stop", "ATR", "Hilbert Envelope/Quadrature", "SMA Detrend", "Z-Score Velocity",
    "Swing High/Low", "Risk:Reward Bracket", "IBS (Internal Bar Strength)", "SMA200", "ATR Stop",
    "Cumulative Volume Delta", "ADX/DMI", "VWAP", "EMA Cross", "Q-Trend Channel", "MFI", "Supertrend",
    "Bollinger Bands", "Volume", "Calendar/Weekday Filter", "EMA", "RSI", "TEMA",
  ],
  // graph edges: strategy -> indicator (built from real pineSource inspection)
  graphEdges: [
    ["ZEC UT P5", "UT Bot / ATR Trailing Stop"], ["ZEC UT P5", "ATR"],
    ["Hilbert F36 ETH", "Hilbert Envelope/Quadrature"], ["Hilbert F36 ETH", "SMA Detrend"], ["Hilbert F36 ETH", "Z-Score Velocity"],
    ["Liquidity Swing v5", "Swing High/Low"], ["Liquidity Swing v5", "ATR"], ["Liquidity Swing v5", "Risk:Reward Bracket"],
    ["HYPE IBS MeanRev", "IBS (Internal Bar Strength)"], ["HYPE IBS MeanRev", "SMA200"], ["HYPE IBS MeanRev", "ATR Stop"],
    ["CVD ADX+VWAP BTC", "Cumulative Volume Delta"], ["CVD ADX+VWAP BTC", "ADX/DMI"], ["CVD ADX+VWAP BTC", "VWAP"], ["CVD ADX+VWAP BTC", "EMA Cross"],
    ["F40D-BE Envelope Gold", "Hilbert Envelope/Quadrature"], ["F40D-BE Envelope Gold", "ADX/DMI"], ["F40D-BE Envelope Gold", "EMA Cross"],
    ["ORDI Q-Trend v3", "Q-Trend Channel"], ["ORDI Q-Trend v3", "MFI"], ["ORDI Q-Trend v3", "ADX/DMI"], ["ORDI Q-Trend v3", "Supertrend"],
    ["SEI BB Breakout ADX v3", "Bollinger Bands"], ["SEI BB Breakout ADX v3", "ADX/DMI"],
    ["SEI Vol-Squeeze Breakout ADX v2", "Bollinger Bands"], ["SEI Vol-Squeeze Breakout ADX v2", "ADX/DMI"], ["SEI Vol-Squeeze Breakout ADX v2", "Volume"],
    ["SUI Vol-Squeeze Breakout ADX v2", "Bollinger Bands"], ["SUI Vol-Squeeze Breakout ADX v2", "ADX/DMI"], ["SUI Vol-Squeeze Breakout ADX v2", "Volume"],
    ["AUDJPY Short-Only Optimized", "Calendar/Weekday Filter"], ["AUDJPY Short-Only Optimized", "EMA"],
    ["RSI Dip & Spike v3.2 PAXG", "RSI"], ["RSI Dip & Spike v3.2 PAXG", "ATR"],
    ["TEMA1h Jesse Port BTC", "TEMA"], ["TEMA1h Jesse Port BTC", "ATR"],
  ],
  strategyMeta: {
    "ZEC UT P5": { symbol: "ZECUSDT", tf: "15m", status: "live", sharpe: 2.29, dd: 16.4, pf: 2.02, winrate: 37, trades: 187,
      source: "UT Bot trailing-stop entry, ATR-based initial stop, 5x leverage on $1,000 margin. Single position, no pyramiding.",
      warnings: [],
      backtests: ["30d: +6.28% net, Sharpe 3.24, PF 2.60, DD 4.38%, 15 trades", "90d: +38.56% net, Sharpe 4.91, PF 4.10, DD 5.50%, 36 trades", "120d: +49.33% net, Sharpe 4.71, PF 3.48, DD 5.45%, 52 trades", "365d: +100.87% net, Sharpe 2.29, PF 2.02, DD 16.37%, 187 trades", "Slippage stress (0-50 ticks): stable, Sharpe 1.8-2.2"] },
    "Hilbert F36 ETH": { symbol: "ETHUSDT", tf: "1h", status: "live", sharpe: 3.78, dd: 15.1, pf: 3.08, winrate: 61, trades: 41,
      source: "Quadrature-filter envelope on detrended price, expansion Z-score + velocity Z-score gate, EMA200 regime filter, breakeven stop.",
      warnings: ["30d window only has 2 trades — statistically too thin to read into on its own"],
      backtests: ["30d: +13.58% net, Sharpe 7.39, 2 trades (low sample)", "90d: +36.44% net, Sharpe 5.17, PF 11.85, DD 4.76%, 8 trades", "120d: +18.42% net, Sharpe 2.19, PF 2.26, DD 14.29%, 13 trades", "365d: +170.47% net, Sharpe 3.78, PF 3.08, DD 15.10%, 41 trades"] },
    "Liquidity Swing v5": { symbol: "ETHUSDT", tf: "1h", status: "live", sharpe: 2.58, dd: 18.1, pf: 2.44, winrate: 49, trades: 51,
      source: "Swing high/low structure break entries, ATR stop, fixed R:R bracket exit (rr=2.8, stopAtrMul=3.2). NOTE: live alert now runs a v2 variant with vol-overlay sizing — numbers below are for the original v5 source, re-verified 2026-07-09.",
      warnings: ["Live alert source was swapped to an unvalidated v2 (vol-overlay sizing) — these backtest numbers are for the prior v5 source, not yet re-run on v2"],
      backtests: ["30d: +11.52% net, Sharpe 3.11, PF 2.83, DD 10.49%, 7 trades", "90d: +15.20% net, Sharpe 1.87, PF 2.03, DD 10.40%, 16 trades", "120d: +22.21% net, Sharpe 1.85, PF 2.08, DD 10.54%, 20 trades", "365d: +193.06% net, Sharpe 2.58, PF 2.44, DD 18.06%, 51 trades"] },
    "HYPE IBS MeanRev": { symbol: "HYPEUSDT", tf: "4h", status: "paused", sharpe: 0.74, dd: 20.1, pf: 1.32, winrate: 59, trades: 139,
      source: "Internal Bar Strength (IBS) mean-reversion long-only, SMA200 trend filter, ATR-multiple hard stop, max-hold bar exit.",
      warnings: ["OOS window (separate from these 4) Sharpe collapsed to -0.02", "365d Sharpe only 0.74 — weak long-run edge even before OOS collapse", "Zero trades in the last 30 days — no recent signal at all", "Max DD 20-24% exceeds acceptable band"],
      backtests: ["30d: no trades (no signal)", "90d: +30.37% net, Sharpe 2.80, PF 2.13, DD 13.40%, 35 trades", "120d: +22.74% net, Sharpe 1.83, PF 1.70, DD 13.40%, 52 trades", "365d: +24.95% net, Sharpe 0.74, PF 1.32, DD 20.08%, 139 trades", "Reactivation re-verified and re-rejected this week"] },
    "CVD ADX+VWAP BTC": { symbol: "BTCUSDT", tf: "15m", status: "rejected", sharpe: -2.01, dd: 2.98, pf: 0.99, winrate: 37, trades: 301,
      source: "Cumulative Volume Delta (bar-level order-flow proxy) EMA-cross signal, gated by ADX trend strength, EMA fast/slow trend filter, VWAP side filter.",
      warnings: ["OOS window Sharpe -2.01, negative net P&L", "12mo window itself already weak (Sharpe 1.02)"],
      backtests: ["12mo: +0.33% net, Sharpe 1.02", "OOS: -2.26% net, Sharpe -2.01"] },
    "F40D-BE Envelope Gold": { symbol: "XAUUSD", tf: "2h", status: "rejected", sharpe: 5.04, dd: 4.17, pf: 7.23, winrate: 63, trades: 16,
      source: "Same quadrature-envelope engine as Hilbert F36, ported to Gold with breakeven stop and fixed TP.",
      warnings: ["Only 16 trades in the only usable window — statistically thin", "XAUUSD 2h history too short for a real OOS test", "Architecturally near-identical to live Hilbert F36 — no true diversification even if verified"],
      backtests: ["Only usable window: Sharpe 5.04, 16 trades", "90d window: data coverage 31% — unusable", "OOS window: data coverage 71%, artifact-level result"] },
    "ORDI Q-Trend v3": { symbol: "ORDIUSDT", tf: "5m", status: "rejected", sharpe: -0.23, dd: 33.2, pf: 1.07, winrate: 46, trades: 223,
      source: "Q-Trend channel breakout (highest/lowest close + ATR band), MFI + ADX confirmation, volume filter, Supertrend bracket exit.",
      warnings: ["OOS window Sharpe -0.23, DD 33.2%", "12mo window looked strong (Sharpe 2.64) — classic instability pattern"],
      backtests: ["12mo: +100.5% net, Sharpe 2.64", "OOS (Jul24-Jul25): -12.0% net, Sharpe -0.23"] },
  },
  // Fingerprint register from Trading Brain Vault (Home.md "Schon getestet") — Symbol|TF|Kategorie|Indikatoren
  // Source of truth for what's already been tested, to avoid repeating backtest ideas in a loop.
  alreadyTried: [
    { fingerprint: "1000BONKUSDT|15|breakout|atr,ema,keltner,sma", count: 1, verdicts: "unprofitable", names: "RESEARCH-2026-07-09-BONK-SqueezeBreakout" },
    { fingerprint: "AVAXUSDT|30|trend_following|atr,ema", count: 1, verdicts: "unprofitable", names: "SMOKE-2026-07-12 AVAX VH 30m Daytrade" },
    { fingerprint: "BNBUSDT|240|mean_reversion|atr,cmf,ema,keltner,rsi,vwma", count: 1, verdicts: "unprofitable", names: "RESEARCH-2026-07-11-BNB-LiquidityReclaim" },
    { fingerprint: "BTCUSDT|240|breakout|atr,donchian", count: 1, verdicts: "excluded_optimizer_run", names: "Vol Squeeze-Release Breakout BTC 4h (Research Desk #2)" },
    { fingerprint: "BTCUSDT|240|trend_following|atr,ema,trailing_stop", count: 1, verdicts: "unprofitable", names: "SMOKE-2026-07-12 EMA200 Trend 4h RiskSized BTC" },
    { fingerprint: "BTCUSDT|60|breakout|bollinger,sma", count: 2, verdicts: "profitable_only", names: "SMOKE-2026-07-12 BB Squeeze Breakout BTC 1h, DEEP-2026-07-12 BB Squeeze Breakout BTC 1h" },
    { fingerprint: "BTCUSDT|60|mean_reversion|bollinger,rsi", count: 1, verdicts: "profitable_only", names: "BTC Mean-Reversion Bollinger+RSI (Original)" },
    { fingerprint: "BTCUSDT|60|mean_reversion|none", count: 1, verdicts: "excluded_optimizer_run", names: "BTC Mean-Reversion Bollinger+RSI (Optimiert, 13 Trades)" },
    { fingerprint: "BTCUSDT|60|momentum|ema,rsi", count: 1, verdicts: "unprofitable", names: "BTC Momentum EMA Crossover 20/50 + RSI" },
    { fingerprint: "BTCUSDT|60|trend_following|adx,atr,ema,rsi,trailing_stop", count: 2, verdicts: "credible, profitable_only", names: "SMOKE-2026-07-12 BTC V7 RSI DI Chandelier, DEEP-2026-07-12 BTC V7 RSI DI Chandelier" },
    { fingerprint: "BTCUSDT|?|breakout|adx,donchian", count: 1, verdicts: "credible", names: "TF-DonchianADX-v8 (Browse-Katalog)" },
    { fingerprint: "BTCUSDT|?|other|none", count: 1, verdicts: "credible", names: "BTC Candle Range Theory (Browse-Katalog)" },
    { fingerprint: "DOGEUSDT|240|mean_reversion|chaikin", count: 1, verdicts: "credible", names: "DOGE Chaikin Z-Score MR v2 (Browse-Katalog)" },
    { fingerprint: "ETHUSDT|60|other|adx,atr,ema", count: 1, verdicts: "credible", names: "SMOKE-2026-07-12 F40D-ADX ETH 1H" },
    { fingerprint: "ETHUSDT|60|other|none", count: 2, verdicts: "credible, excluded_optimizer_run", names: "Realized-Vol Risk Overlay -- Liquidity Swing v5 (90pct/0.5x, LIVE DEPLOYED), Realized-Vol Risk Overlay -- Hilbert F36 (extra dampening, ZURUECKGESTELLT)" },
    { fingerprint: "HYPEUSDT|15|other|adx,t3", count: 1, verdicts: "credible", names: "HYPE DemonDays PH Cross ADX-DI Filter (Browse-Katalog)" },
    { fingerprint: "HYPEUSDT|15|other|none", count: 1, verdicts: "credible", names: "HYPE UT P5 (Cross-Coin-Test, identischer Code)" },
    { fingerprint: "HYPEUSDT|240|mean_reversion|atr,ibs,sma", count: 1, verdicts: "credible", names: "HYPE IBS MeanRev 4h" },
    { fingerprint: "ORDIUSDT|5|trend_following|adx,atr,sma,supertrend", count: 1, verdicts: "credible", names: "ORDI 5m Q-Trend v3 (Original p=30 mult=1.2)" },
    { fingerprint: "WIFUSDT|15|momentum|atr,macd", count: 1, verdicts: "unprofitable", names: "RESEARCH-2026-07-10-WIF-MomentumThrust" },
    { fingerprint: "ZECUSDT|15|other|ema,rsi,trailing_stop", count: 1, verdicts: "credible", names: "ZEC UT P5 (Original Compounding)" },
    { fingerprint: "ZECUSDT|15|other|none", count: 1, verdicts: "credible", names: "ZEC UT P5 (Out-of-Sample Verify)" },
    { fingerprint: "ZECUSDT|15|trend_following|trailing_stop", count: 1, verdicts: "excluded_optimizer_run", names: "Realized-Vol Risk Overlay -- ZEC UT P5 (rekalibriert, VERWORFEN)" },
    { fingerprint: "ZECUSDT|240|breakout|none", count: 1, verdicts: "profitable_only", names: "Vol Squeeze-Release Breakout ZEC 4h (Bugfix-Vergleich)" },
  ],
};
